Vagrant.configure("2") do |config|
 config.vm.define:centos do |centos_config|
   centos_config.vm.box = "chef/centos-6.5"
   centos_config.vm.host_name = "centos"
   centos_config.vm.network "private_network", ip:"192.168.100.10"
   #config.vm.provider :virtualbox do |vb|
   #    vb.customize ["modifyvm", :id, "--memory", "2048"]
   #    vb.customize ["modifyvm", :id, "--cpus", "2"]
   #end
 end

 config.vm.define:ubuntu do |ubuntu_config|
   ubuntu_config.vm.box = "ubuntu/trusty64"
   ubuntu_config.vm.host_name = "ubuntu"
   ubuntu_config.vm.network "private_network", ip:"192.168.100.20"
   #config.vm.provider :virtualbox do |vb|
   #    vb.customize ["modifyvm", :id, "--memory", "1024"]
   #    vb.customize ["modifyvm", :id, "--cpus", "2"]
   #end
 end

 config.vm.define:fedora do |fedora_config|
   fedora_config.vm.box = "chef/fedora-20"
   fedora_config.vm.host_name = "fedora"
   fedora_config.vm.network "private_network", ip:"192.168.100.30"
   #config.vm.provider :virtualbox do |vb|
   #    vb.customize ["modifyvm", :id, "--memory", "1024"]
   #    vb.customize ["modifyvm", :id, "--cpus", "2"]
   #end
 end

end
