Vagrant.configure(2) do |config|  
  config.vm.define :ubuntu1 do |ubuntu1_config|
     ubuntu1_config.vm.box = “ubuntu/trusty64”
     ubuntu1_config.vm.host_name = “ubuntu1”
     ubuntu1_config.vm.network “private_network”, ip:”192.168.100.10”
     #config.vm.provider :virtualbox do |vb|
     #    vb.customize ["modifyvm", :id, "--memory", "2048”]
     #    vb.customize ["modifyvm", :id, "--cpus", "2"]
     #end
  end

  config.vm.define :ubuntu2 do |ubuntu2_config|
     ubuntu2_config.vm.box = “ubuntu/trusty64”
     ubuntu2_config.vm.host_name = “ubuntu2”
     ubuntu2_config.vm.network “private_network”, ip:”192.168.100.20”
     #config.vm.provider :virtualbox do |vb|
     #    vb.customize ["modifyvm", :id, "--memory", "2048"]
     #    vb.customize ["modifyvm", :id, "--cpus", "2"]
     #end
  end

end